---
- name: Setup Sakila Database
  hosts: master
  tasks:
    - name: Check if sakila is present
      shell: echo | mysql -s sakila
      register: sakila_found
      always_run: yes
      ignore_errors: yes
    
    - name: Download sakila gz
      get_url:
        url: http://downloads.mysql.com/docs/sakila-db.tar.gz
        dest: /root
      when: sakila_found|failed
      register: sakila_downloaded
    
    - name: Extract gz
      unarchive:
        copy: no
        src: /root/sakila-db.tar.gz
        dest: /root
      when: sakila_downloaded|changed
      register: sakila_extracted
    
    - name: Load sakila database
      shell: "mysql < /root/{{ item }}"
      when: sakila_extracted|changed
      with_items:
        - sakila-db/sakila-schema.sql
        - sakila-db/sakila-data.sql
