- name: Set up OS
  hosts: all
  tasks:
    - name: Install EPEL
      yum: name=epel-release state=present
      
    - name: Install Handy Tools
      yum: name={{ item }} state=present
      with_items:
        - nc
        - socat
        - lsof
        - wget
        - curl
        - screen
        - tmux
        - sysstat
        - ntp
        - ntpdate
        - telnet
        - unzip
        - bind-utils
        - vim
        - perf
        - libselinux-python

    - name: Manage Services
      service: name={{ item.name }} state={{ item.state }}
      with_items:
        - name: ntpd
          state: running
        - name: firewalld
          state: stopped

    - name: Ensure SELINUX is permissive
      selinux: state=permissive policy=targeted
